name: Github actions emulator
on:
    push:
      branches:
        - wip-uia
    workflow_dispatch:
jobs:
    instrumented-tests:
      name: uia tests
      timeout-minutes: 60
      strategy:
        matrix:
          # os: [macos-latest]
          api: [32] #26, 27, 28, 29, 30, 31, 32 ,33
          emutype: [google_apis] # default, aosp_atd, google_apis, playstore

          include:
            # - os: ubuntu-latest
            #   emulator-options: -no-snapshot-save -no-window -noaudio -no-boot-anim -camera-back none
            - os: macos-latest
              emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none

        fail-fast: false
      runs-on: self-hosted
      steps:
          # - name: Java 11
          #   uses: actions/setup-java@v1
          #   with:
          #     java-version: 11
          - name: Checkout repository
            uses: actions/checkout@v3
          - name: Build
            shell: bash
            run: |
              github-actions-emulator/gradlew -p github-actions-emulator installDebug

          # - name: Run Android instrumented tests
          #   uses: reactivecircus/android-emulator-runner@v2
          #   continue-on-error: true
          #   env:
          #     API_LEVEL: ${{ matrix.api }}
          #   with:
          #     force-avd-creation: true # TODO: Set to false
          #     api-level: ${{ matrix.api }}
          #     target: ${{ matrix.emutype }}
          #     arch: x86_64
          #     emulator-options: ${{ matrix.emulator-options }}
          #     disable-animations: true
          #     profile: pixel
          #     script: |
          #       github-actions-emulator/gradlew -p github-actions-emulator installDebug
          #       adb shell am start -n com.albin_mullvad.gh_actions_emulator/.MainActivity
          #       adb shell mkdir /sdcard/capture
          #       sleep 10
          #       adb shell screencap /sdcard/capture/mycap1.png
          #       adb shell uiautomator dump -f /sdcard/capture/mydump.xml
          #       adb shell screencap /sdcard/capture/mycap2.png
          #       adb pull /sdcard/capture github-actions-emulator/app/build/outputs
              
          #     #github-actions-emulator/gradlew -p github-actions-emulator connectedCheck
          # - name: Upload outputs and reports
          #   uses: actions/upload-artifact@v3
          #   with:
          #     name: outputs-and-reports-${{ matrix.os }}
          #     path: |
          #       github-actions-emulator/app/build/outputs
          #       github-actions-emulator/app/build/reports
          #     # if-no-files-found: error
          #     retention-days: 1
