name: Github actions emulator
on:
    push:
      branches:
        - wip-uia
    workflow_dispatch:
jobs:
    instrumented-tests:
        name: uia tests
        runs-on: macos-latest
        timeout-minutes: 60
        strategy:
            matrix:
              api: [32] #26, 27, 28, 29, 30, 31, 32 ,33
              emutype: [google_apis] # default, aosp_atd, google_apis, playstore
            fail-fast: false
        steps:
            - name: Java 11
              uses: actions/setup-java@v1
              with:
                java-version: 11

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Run Android instrumented tests
              uses: reactivecircus/android-emulator-runner@v2
              continue-on-error: true
              env:
                API_LEVEL: ${{ matrix.api }}
              with:
                force-avd-creation: true # TODO: Set to false
                api-level: ${{ matrix.api }}
                target: ${{ matrix.emutype }}
                arch: x86_64
                emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                disable-animations: true
                profile: pixel
                script: github-actions-emulator/gradlew -p github-actions-emulator connectedCheck

            - name: Upload outputs and reports
              uses: actions/upload-artifact@v3
              with:
                name: outputs-and-reports
                path: |
                  github-actions-emulator/app/build/outputs
                  github-actions-emulator/app/build/reports
                if-no-files-found: error
                retention-days: 1
